In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("retail_sales_dataset.csv")
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200

In [4]:
df.shape

(1000, 9)

In [5]:
df.columns

Index(['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age',
       'Product Category', 'Quantity', 'Price per Unit', 'Total Amount'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [7]:
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

#### Transformacion de datos(para trabajar de manera formateada)

In [9]:
df["Date"]= pd.to_datetime(df["Date"])
df["Month"]= df["Date"].dt.month
df["Year"]= df["Date"].dt.year

#### Clasificar las ventas en Alta, Media y Baja
van aproximadamente desde 25 hasta 2000(se dejara valores alta media y baja a base de los datos que se menciono)

In [10]:
def clasificar_ventas(total):
    if total >= 1000:
        return "alta"
    elif total >= 500:
        return "media"
    else:
        return "baja"
    
df["Sales Category"] = df["Total Amount"].apply(clasificar_ventas)

df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Month,Year,Sales Category
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,11,2023,baja
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,2,2023,alta
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,1,2023,baja
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,5,2023,media
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,5,2023,baja

#### Agrupación y agregación

In [11]:
ventas_por_categoria = df.groupby("Product Category")["Total Amount"].sum()
ventas_por_categoria

Product Category
Beauty         143515
Clothing       155580
Electronics    156905
Name: Total Amount, dtype: int64

In [16]:
ventas_por_mes = df.groupby(["Product Category", "Month"])["Total Amount"].sum()
ventas_por_mes

Product Category  Month
Beauty            1        13930
                  2        14035
                  3        10545
                  4        11905
                  5        12450
                  6        10995
                  7        16090
                  8         9790
                  9         6320
                  10       15355
                  11        9700
                  12       12400
Clothing          1        13125
                  2        14560
                  3        15065
                  4        13940
                  5        17455
                  6        10170
                  7         8250
                  8        12455
                  9         9975
                  10       13315
                  11       15200
                  12       12070
Electronics       1         9925
                  2        15465
                  3         3380
                  4         8025
                  5        23245
                  6        15550
                  7        11125
                  8        14715
                  9         7325
                  10       17910
                  11       10020
                  12       20220
Name: Total Amount, dtype: int64

In [17]:
ventas_por_year = df.groupby(["Product Category", "Year"])["Total Amount"].sum()
ventas_por_year

Product Category  Year
Beauty            2023    142015
                  2024      1500
Clothing          2023    155580
Electronics       2023    156875
                  2024        30
Name: Total Amount, dtype: int64

#### Estadísticas por categoria, funciones de agregación

In [18]:
estadisticas_categoria = df.groupby("Product Category")["Total Amount"].agg(["sum","mean","count","min","max","std","var"])

estadisticas_categoria

,sum,mean,count,min,max,std,var
Product Category,,,,,,,
Beauty,143515,467.475570,307,25,2000,563.612788,317659.374401
Clothing,155580,443.247863,351,25,2000,550.695917,303265.992674
Electronics,156905,458.786550,342,25,2000,567.540150,322101.822341

In [19]:
ventas_genero_categoria = df.groupby(["Gender", "Product Category"])["Total Amount"].agg(["sum","mean","count","min","max"])

ventas_genero_categoria

                           sum        mean  count  min   max
Gender Product Category
Female Beauty            74830  450.783133    166   25  2000
       Clothing          81275  467.097701    174   25  2000
       Electronics       76735  451.382353    170   25  2000
Male   Beauty            68685  487.127660    141   25  2000
       Clothing          74305  419.802260    177   25  2000
       Electronics       80170  466.104651    172   25  2000

In [20]:
resumen_categoria_venta = df.groupby("Sales Category")["Total Amount"].agg(["sum","mean","count","min","max","std","var"])

resumen_categoria_venta

,sum,mean,count,min,max,std,var
Sales Category,,,,,,,
alta,286800,1419.801980,202,1000,2000,373.638770,139605.930742
baja,66900,102.923077,650,25,300,73.480458,5399.377741
media,102300,691.216216,148,500,900,181.800913,33051.571980

#### Análisis Personalizado con apply
Comparar cada venta con el promedio general

In [21]:
promedio_general = df["Total Amount"].mean()

promedio_general

np.float64(456.0)

In [22]:
def comparar_con_promedio(total):
    if total > promedio_general:
        return "Sobre el promedio"
    elif total < promedio_general:
        return "Bajo el promedio"
    else:
        return "Igual al promedio"

In [23]:
df["Comparison With Average"] = df["Total Amount"].apply(comparar_con_promedio)
df[["Total Amount", "Comparison With Average"]].head(10)

   Total Amount Comparison With Average
0           150        Bajo el promedio
1          1000       Sobre el promedio
2            30        Bajo el promedio
3           500       Sobre el promedio
4           100        Bajo el promedio
5            30        Bajo el promedio
6            50        Bajo el promedio
7           100        Bajo el promedio
8           600       Sobre el promedio
9           200        Bajo el promedio

#### Desviación de cada venta respecto a la media de su grupo

In [24]:
df["Group Average"] = df.groupby("Product Category")["Total Amount"].transform("mean")
df["Deviation From Group Mean"] = df["Total Amount"] - df["Group Average"]
df[["Product Category", "Total Amount", "Group Average", "Deviation From Group Mean"]].head(10)

  Product Category  Total Amount  Group Average  Deviation From Group Mean
0           Beauty           150     467.475570                -317.475570
1         Clothing          1000     443.247863                 556.752137
2      Electronics            30     458.786550                -428.786550
3         Clothing           500     443.247863                  56.752137
4           Beauty           100     467.475570                -367.475570
5           Beauty            30     467.475570                -437.475570
6         Clothing            50     443.247863                -393.247863
7      Electronics           100     458.786550                -358.786550
8      Electronics           600     458.786550                 141.213450
9         Clothing           200     443.247863                -243.247863

In [26]:
def interpretar_desviacion(valor):
    if valor > 0:
        return "Mayor que el promedio de su categoría"
    elif valor < 0:
        return "Menor que el promedio de su categoría"
    else:
        return "Igual al promedio de su categoría"
    
df["Deviation Analysis"] = df["Deviation From Group Mean"].apply(interpretar_desviacion)

df[["Product Category","Total Amount","Group Average","Deviation From Group Mean","Deviation Analysis"]].head(10)

,Product Category,Total Amount,Group Average,Deviation From Group Mean,Deviation Analysis
0,Beauty,150,467.475570,-317.475570,Menor que el promedio de su categoría
1,Clothing,1000,443.247863,556.752137,Mayor que el promedio de su categoría
2,Electronics,30,458.786550,-428.786550,Menor que el promedio de su categoría
3,Clothing,500,443.247863,56.752137,Mayor que el promedio de su categoría
4,Beauty,100,467.475570,-367.475570,Menor que el promedio de su categoría
5,Beauty,30,467.475570,-437.475570,Menor que el promedio de su categoría
6,Clothing,50,443.247863,-393.247863,Menor que el promedio de su categoría
7,Electronics,100,458.786550,-358.786550,Menor que el promedio de su categoría
8,Electronics,600,458.786550,141.213450,Mayor que el promedio de su categoría
9,Clothing,200,443.247863,-243.247863,Menor que el promedio de su categoría